import Vue from 'vue'
import Vuex from 'vuex'
import mutations from './mutations'
import actions from './action'

Vue.use(Vuex);

const state={
	totalTime:0,
	list:[
		{
			name:'张',
			avatar:'../assets/img.png',
			date:'2017/4/1',
			totalTime:'6',
			comment:'今天会已经开完了！！！'
		},
		{
			name:'gainloss',
			avatar:'../assets/img.png',
			date:'2017/4/2',
			totalTime:'6',
			comment:'休息休息'
		},
		{
			name:'gainloss',
			avatar:'../assets/img.png',
			date:'2017/4/3',
			totalTime:'6',
			comment:'还是休息'
		},
		
	],
	listnew:[
		{
			name:'gainloss',
			photo:'./././assets/1.png',
			age:12,
			comment:'明天休息哈哈'
		},
		{
			name:'gainloss',
			age:12,
			comment:'明天休息哈哈'
		},
		{
			name:'gainloss',
			age:12,
			comment:'明天休息哈哈'
		},
		{
			name:'gainloss',
			age:12,
			comment:'明天休息哈哈'
		},
		{
			name:'gainloss',
			age:12,
			comment:'明天休息哈哈'
		},
		{
			name:'gainloss',
			age:12,
			comment:'明天休息哈哈'
		},
		{
			name:'gainloss',
			age:12,
			comment:'明天休息哈哈'
		},
		{
			name:'gainloss',
			age:12,
			comment:'明天休息哈哈'
		},
		{
			name:'gainloss',
			age:12,
			comment:'明天休息哈哈'
		},
	],
	//home主页中精选的数据
	home:[
		{
			title:'一个精简、全面、方便的Androild库',
			img:'../../../static/jingxuan/1.png',
			like:30,
			user:'blankj',
			time:'2017:4:10:15:3:3',
			url:'http:baidu.com'
		},
		{
			title:'[科普文]二维码的生成和扫码',
			img:'../../../static/jingxuan/2.png',
			like:32,
			user:'美团金融前端团队',
			time:'2017:4:2:15:3:3',
			url:'http:baidu.com'
		},
		{
			title:'《Objective-C 高级编程》干货三部曲（一）：引用技术篇',
			img:'../../../static/jingxuan/3.jpg',
			like:30,
			user:'J_Knight',
			time:'2017:11:10:15:3:3',
			url:'http:baidu.com'
		},
		{
			title:'我是如果用200行代码写出一个RESTful微框架',
			img:'../../../static/jingxuan/4.jpg',
			like:30,
			user:'leontung',
			time:'2017:12:10:15:3:3',
			url:'http:baidu.com'
		},
	],
	//android
	android:[
		{
			title:'App开发：模拟服务器数据接口-MockApi',
			img:'../../../static/jingxuan/1.png',
			like:5,
			user:'jiuzhang',
			time:'2017:4:10:15:3:3',
			url:'http:baidu.com'
		},
		{
			title:'完整项目练手：仿《一个one》App',
			img:'../../../static/jingxuan/2.png',
			like:32,
			user:'LiuZh',
			time:'2017:4:2:15:3:3',
			url:'http:baidu.com'
		},
		{
			title:'Android之Notification必须掌握知识点',
			img:'../../../static/jingxuan/3.jpg',
			like:30,
			user:'code小生',
			time:'2017:11:10:15:3:3',
			url:'http:baidu.com'
		},
		{
			title:'Android教你打造独一无二的刷新加载框架',
			img:'../../../static/jingxuan/5.jpg',
			like:30,
			user:'leontung',
			time:'2017:12:10:15:3:3',
			url:'http:baidu.com'
		},
	],
	//标签
	labelheat:[
		{
			title:'前端',
			photo:'../../../static/label/1.png',
			follow:7359,
			article:1840
		},
		{
			title:'Github',
			photo:'../../../static/label/2.png',
			follow:2345,
			article:3210
		},
		{
			title:'Android',
			photo:'../../../static/label/3.png',
			follow:35,
			article:1840
		},
		{
			title:'后端',
			photo:'../../../static/label/4.png',
			follow:2345,
			article:3210
		},
		{
			title:'前端',
			photo:'../../../static/label/1.png',
			follow:7359,
			article:1840
		},
		{
			title:'Github',
			photo:'../../../static/label/2.png',
			follow:2345,
			article:3210
		},
		{
			title:'Android',
			photo:'../../../static/label/3.png',
			follow:35,
			article:1840
		},
		{
			title:'后端',
			photo:'../../../static/label/4.png',
			follow:2345,
			article:3210
		},{
			title:'前端',
			photo:'../../../static/label/1.png',
			follow:7359,
			article:1840
		},
		{
			title:'Github',
			photo:'../../../static/label/2.png',
			follow:2345,
			article:3210
		},
		{
			title:'Android',
			photo:'../../../static/label/3.png',
			follow:35,
			article:1840
		},
		{
			title:'后端',
			photo:'../../../static/label/4.png',
			follow:2345,
			article:3210
		},{
			title:'前端',
			photo:'../../../static/label/1.png',
			follow:7359,
			article:1840
		},
		{
			title:'Github',
			photo:'../../../static/label/2.png',
			follow:2345,
			article:3210
		},
		{
			title:'Android',
			photo:'../../../static/label/3.png',
			follow:35,
			article:1840
		},
		{
			title:'后端',
			photo:'../../../static/label/4.png',
			follow:2345,
			article:3210
		},
	],
	labelnew:[
		{
			title:'rollup.js',
			photo:'../../../static/label/new/1.png',
			follow:7359,
			article:1840
		},
		{
			title:'数据分析',
			photo:'../../../static/label/new/2.png',
			follow:2345,
			article:3210
		},
		{
			title:'E2E',
			photo:'../../../static/label/new/3.png',
			follow:35,
			article:1840
		},
		{
			title:'Omi',
			photo:'../../../static/label/new/4.png',
			follow:2345,
			article:3210
		},
		{
			title:'rollup.js',
			photo:'../../../static/label/new/1.png',
			follow:7359,
			article:1840
		},
		{
			title:'数据分析',
			photo:'../../../static/label/new/2.png',
			follow:2345,
			article:3210
		},
		{
			title:'E2E',
			photo:'../../../static/label/new/3.png',
			follow:35,
			article:1840
		},
		{
			title:'Omi',
			photo:'../../../static/label/new/4.png',
			follow:2345,
			article:3210
		},
		{
			title:'rollup.js',
			photo:'../../../static/label/new/1.png',
			follow:7359,
			article:1840
		},
		{
			title:'数据分析',
			photo:'../../../static/label/new/2.png',
			follow:2345,
			article:3210
		},
		{
			title:'E2E',
			photo:'../../../static/label/new/3.png',
			follow:35,
			article:1840
		},
		{
			title:'Omi',
			photo:'../../../static/label/new/4.png',
			follow:2345,
			article:3210
		},
		{
			title:'rollup.js',
			photo:'../../../static/label/new/1.png',
			follow:7359,
			article:1840
		},
		{
			title:'数据分析',
			photo:'../../../static/label/new/2.png',
			follow:2345,
			article:3210
		},
		{
			title:'E2E',
			photo:'../../../static/label/new/3.png',
			follow:35,
			article:1840
		},
		{
			title:'Omi',
			photo:'../../../static/label/new/4.png',
			follow:2345,
			article:3210
		},	
	],
	//收藏集
	newlist:[
		{
			title:'Angular',
			photo:'../../../static/newlist/1.jpg',
			follow:11,
			article:'zhang'
		},
		{
			title:'Angular',
			photo:'../../../static/newlist/1.jpg',
			follow:11,
			article:'zhang'
		},
		{
			title:'Angular',
			photo:'../../../static/newlist/1.jpg',
			follow:11,
			article:'zhang'
		},
		{
			title:'Angular',
			photo:'../../../static/newlist/1.jpg',
			follow:11,
			article:'zhang'
		},{
			title:'Angular',
			photo:'../../../static/newlist/1.jpg',
			follow:11,
			article:'zhang'
		},
		{
			title:'Angular',
			photo:'../../../static/newlist/1.jpg',
			follow:11,
			article:'zhang'
		},
		{
			title:'Angular',
			photo:'../../../static/newlist/1.jpg',
			follow:11,
			article:'zhang'
		},
		{
			title:'Angular',
			photo:'../../../static/newlist/1.jpg',
			follow:11,
			article:'zhang'
		},
	],
	special:[
		{
			userimg:'../../../static/special/1.png',
			autor:'zhang',
			time:2,
			bigphoto:'../../../static/special/2.png',
			title:'Ionic2入门教程 实现TodoList App-2 实现TodoList App',
			container:'在上一篇教程Ionic2入门教程 实现TodoList App-1 初识Ionic2 中，我们介绍了Ionic2框架和使用Ionic2的命令行工具创建一个项目，并介绍了创建的项目结构和各个部分。在这一部分教程中，我们还是来实现一个TodoList的实例，来看看怎么用Ionic2…',
		},
		{
			userimg:'../../../static/special/1.png',
			autor:'zhang',
			time:2,
			bigphoto:'../../../static/special/2.png',
			title:'Ionic2入门教程 实现TodoList App-2 实现TodoList App',
			container:'在上一篇教程Ionic2入门教程 实现TodoList App-1 初识Ionic2 中，我们介绍了Ionic2框架和使用Ionic2的命令行工具创建一个项目，并介绍了创建的项目结构和各个部分。在这一部分教程中，我们还是来实现一个TodoList的实例，来看看怎么用Ionic2…',
		},
		{
			userimg:'../../../static/special/1.png',
			autor:'zhang',
			time:2,
			bigphoto:'../../../static/special/2.png',
			title:'Ionic2入门教程 实现TodoList App-2 实现TodoList App',
			container:'在上一篇教程Ionic2入门教程 实现TodoList App-1 初识Ionic2 中，我们介绍了Ionic2框架和使用Ionic2的命令行工具创建一个项目，并介绍了创建的项目结构和各个部分。在这一部分教程中，我们还是来实现一个TodoList的实例，来看看怎么用Ionic2…',
		},
		{
			userimg:'../../../static/special/1.png',
			autor:'zhang',
			time:2,
			bigphoto:'../../../static/special/2.png',
			title:'Ionic2入门教程 实现TodoList App-2 实现TodoList App',
			container:'在上一篇教程Ionic2入门教程 实现TodoList App-1 初识Ionic2 中，我们介绍了Ionic2框架和使用Ionic2的命令行工具创建一个项目，并介绍了创建的项目结构和各个部分。在这一部分教程中，我们还是来实现一个TodoList的实例，来看看怎么用Ionic2…',
		},
		{
			userimg:'../../../static/special/1.png',
			autor:'zhang',
			time:2,
			bigphoto:'../../../static/special/2.png',
			title:'Ionic2入门教程 实现TodoList App-2 实现TodoList App',
			container:'在上一篇教程Ionic2入门教程 实现TodoList App-1 初识Ionic2 中，我们介绍了Ionic2框架和使用Ionic2的命令行工具创建一个项目，并介绍了创建的项目结构和各个部分。在这一部分教程中，我们还是来实现一个TodoList的实例，来看看怎么用Ionic2…',
		},
		{
			userimg:'../../../static/special/1.png',
			autor:'zhang',
			time:2,
			bigphoto:'../../../static/special/2.png',
			title:'Ionic2入门教程 实现TodoList App-2 实现TodoList App',
			container:'在上一篇教程Ionic2入门教程 实现TodoList App-1 初识Ionic2 中，我们介绍了Ionic2框架和使用Ionic2的命令行工具创建一个项目，并介绍了创建的项目结构和各个部分。在这一部分教程中，我们还是来实现一个TodoList的实例，来看看怎么用Ionic2…',
		},
		{
			userimg:'../../../static/special/1.png',
			autor:'zhang',
			time:2,
			bigphoto:'../../../static/special/2.png',
			title:'Ionic2入门教程 实现TodoList App-2 实现TodoList App',
			container:'在上一篇教程Ionic2入门教程 实现TodoList App-1 初识Ionic2 中，我们介绍了Ionic2框架和使用Ionic2的命令行工具创建一个项目，并介绍了创建的项目结构和各个部分。在这一部分教程中，我们还是来实现一个TodoList的实例，来看看怎么用Ionic2…',
		},
		{
			userimg:'../../../static/special/1.png',
			autor:'zhang',
			time:2,
			bigphoto:'../../../static/special/2.png',
			title:'Ionic2入门教程 实现TodoList App-2 实现TodoList App',
			container:'在上一篇教程Ionic2入门教程 实现TodoList App-1 初识Ionic2 中，我们介绍了Ionic2框架和使用Ionic2的命令行工具创建一个项目，并介绍了创建的项目结构和各个部分。在这一部分教程中，我们还是来实现一个TodoList的实例，来看看怎么用Ionic2…',
		},
		{
			userimg:'../../../static/special/1.png',
			autor:'zhang',
			time:2,
			bigphoto:'../../../static/special/2.png',
			title:'Ionic2入门教程 实现TodoList App-2 实现TodoList App',
			container:'在上一篇教程Ionic2入门教程 实现TodoList App-1 初识Ionic2 中，我们介绍了Ionic2框架和使用Ionic2的命令行工具创建一个项目，并介绍了创建的项目结构和各个部分。在这一部分教程中，我们还是来实现一个TodoList的实例，来看看怎么用Ionic2…',
		},
		{
			userimg:'../../../static/special/1.png',
			autor:'zhang',
			time:2,
			bigphoto:'../../../static/special/2.png',
			title:'Ionic2入门教程 实现TodoList App-2 实现TodoList App',
			container:'在上一篇教程Ionic2入门教程 实现TodoList App-1 初识Ionic2 中，我们介绍了Ionic2框架和使用Ionic2的命令行工具创建一个项目，并介绍了创建的项目结构和各个部分。在这一部分教程中，我们还是来实现一个TodoList的实例，来看看怎么用Ionic2…',
		},
	],
	specialSort:[
		{
			containre:'破解前端面试（80% 应聘者不及格系列）：从闭包说起',
			link:300,
			leavingmessage:30
		},
		{
			containre:'破解前端面试（80% 应聘者不及格系列）：从闭包说起',
			link:300,
			leavingmessage:30
		},
		{
			containre:'破解前端面试（80% 应聘者不及格系列）：从闭包说起',
			link:300,
			leavingmessage:30
		},
		{
			containre:'破解前端面试（80% 应聘者不及格系列）：从闭包说起',
			link:300,
			leavingmessage:30
		},
		{
			containre:'破解前端面试（80% 应聘者不及格系列）：从闭包说起',
			link:300,
			leavingmessage:30
		}
	]
};


export default new Vuex.Store({
	state,
	mutations,
	actions,

})
